---
name: Esoteric-Loader
author: ethaniccc
description: A loader for the Esoteric anti-cheat
version: 1.0.0
main: ethaniccc\Loader\Loader
api: 3.19.0
mcpe-protocol: [431, 440, 448, 465, 471]
extensions:
  Core: ">=7.4"
permissions:
  ac:
    description: Gives all anticheat permissions
    default: op
    children:
      ac.alerts:
        description: Gives access to anticheat alerts
        default: op
      ac.bypass:
        description: Allows to bypass anticheat punishments
        default: op
      ac.command:
        description: Allows for all usages of the anticheat command
        default: op
        children:
          ac.command.help:
            description: Access to the anticheat's help command
            default: op
          ac.command.logs:
            description: Access to get the anticheat logs of a player
            default: op
          ac.command.delay:
            description: Access to change the alert delay
            default: op
          ac.command.banwave:
            description: Handle Esoteric ban waves
            default: op
            children:
              ac.command.banwave.add:
                description: Create a new banwave in the Esoteric anti-cheat
                default: op
              ac.command.banwave.execute:
                description: Execute a banwave in the Esoteric anti-cheat
                default: op
              ac.command.banwave.remove:
                description: Remove an existing Esoteric banwave
                default: op
              ac.command.banwave.undo:
                description: Undo the punishments executed from a specified banwave
                default: op
          ac.command.timings:
            description: Enable timings for a certain period of time to see server performance with Esoteric
            default: op
          ac.command.exempt:
            description: Get access to exempt sub commands in Esoteric
            default: op
            children:
              ac.command.exempt.add:
                description: Add a player to an exempt list
                default: op
              ac.command.exempt.all:
                description: Get all the currently exempted players
                default: op
              ac.command.exempt.get:
                description: Check if a target player is exempt or not
                default: op
              ac.command.exempt.remove:
                description: Remove a player to an exempt list
                default: op
          ac.command.debug:
            description: Get access to debugging commands in Esoteric
            default: op
